project:
  type: book

book:
  title: "APRENDIZADO DE MÁQUINA COM R"
  reader-mode: true
  back-to-top-navigation: true
  search: true
  repo-actions: [issue]
  sharing: [twitter,facebook,linkedin]
  favicon: uff-brasao.jpg
  page-footer:
    left: |
      Orientação: Douglas Rodrigues (UFF) e Karina Yaginuma (UFF). <br>
      Equipe atual: Gabriel Caetano, Guilherme Ceacero, Claudionor Ferreira e Fenício Porto.
  repo-url: https://github.com/CienciaDeDadosUFF/R.github.io
  downloads: [pdf]
  
  chapters:
    - index.qmd
    - intro.qmd
    - tipos-am.qmd
    - pred.qmd
    - design-pred.qmd
    - erros-amostrais.qmd
    - caret.qmd
    - cross-valid.qmd
    - comp-func.qmd
    - pre-processamento.qmd
    - metodos-de-treino-baseados-em-arvore.qmd
    - outros-metodos.qmd
    - referencias.qmd



bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual

knitr: 
  opts_chunk: 
    warning: false 
    message: false